ReefAquarium.Web/Models/Aquariums/AquariumFormModel.cs
namespace ReefAquarium.Web.Models.Aquariums
{
    using ReefAquarium.Data;
    using System.ComponentModel.DataAnnotations;

    public class AquariumFormModel
    {
        [Required]
        [MinLength(DataConstants.AquariumTitleMinLength)]
        [MaxLength(DataConstants.AquariumTitleMaxLength)]
        public string Title { get; set; }

        //in cm
        public int Length { get; set; }

        //in cm
        public int Width { get; set; }

        //in cm
        public int Height { get; set; }

        [Required]
        [MaxLength(DataConstants.AquariumDescriptionMaxLength)]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Image Url")]
        public string ImageUrl { get; set; }
    }
}

ReefAquarium.Web/Controllers/AquariumsController.cs
namespace ReefAquarium.Web.Controllers
{
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Aquariums;
    using Services;
    using System.Threading.Tasks;

    public class AquariumsController : Controller
    {
        private readonly IAquariumService aquariums;
        private readonly UserManager<User> userManager;
        private readonly ICommentService comments;

        public AquariumsController(
            IAquariumService aquariums,
            UserManager<User> userManager,
            ICommentService comments)
        {
            this.aquariums = aquariums;
            this.userManager = userManager;
            this.comments = comments;
        }

        [Authorize]
        public IActionResult Create()
            => View();

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(AquariumFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.aquariums.CerateAsync(
                model.Title,
                model.Length,
                model.Width,
                model.Height,
                model.Description,
                model.ImageUrl,
                this.userManager.GetUserId(User));

            return RedirectToAction(nameof(AquariumsController.All), "Aquariums", new { area = string.Empty });
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var aquarium = await this.aquariums.ById(id);
            var userId = this.userManager.GetUserId(User);

            if (aquarium == null)
            {
                return NotFound();
            }

            if (!await this.aquariums.UserIsOwner(id, userId))
            {
                return BadRequest();
            }

            return View(new AquariumFormModel
            {
                Title = aquarium.Title,
                Length = aquarium.Length,
                Width = aquarium.Width,
                Height = aquarium.Height,
                Description = aquarium.Description,
                ImageUrl = aquarium.ImageUrl
            });          
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, AquariumFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.aquariums.EditAsync(
                id,
                model.Title,
                model.Length,
                model.Width,
                model.Height,
                model.Description,
                model.ImageUrl);

            return RedirectToAction(nameof(AquariumsController.Details), "Aquariums", new { id });
        }

        public async Task<IActionResult> All()
            => View(await this.aquariums.AllAsync());

        public async Task<IActionResult> Details(int id)
        {
            var model = await this.aquariums.ById(id);

            if (model == null)
            {
                return NotFound();
            }

            if (User.Identity.IsAuthenticated)
            {
                var userId = userManager.GetUserId(User);

                model.UserIsOwner = await this.aquariums.UserIsOwner(id, userId);
            }

            return View(model);
        }
    }
}

ReefAquarium.Web/Controllers/BreedsController.cs
namespace ReefAquarium.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services;
    using System.Threading.Tasks;

    public class BreedsController : Controller
    {
        private readonly IBreedService breeds;

        public BreedsController(IBreedService breeds)
        {
            this.breeds = breeds;
        }

        public async Task<IActionResult> All()
            => View(await this.breeds.AllAsync());

        public async Task<IActionResult> Details(int id)
            => View(await this.breeds.ById(id));
    }
}

ReefAquarium.Web/Controllers/CommentsController.cs
namespace ReefAquarium.Web.Controllers
{
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Services;
    using System.Threading.Tasks;

    public class CommentsController : Controller
    {
        private readonly ICommentService comments;
        private readonly UserManager<User> userManager;

        public CommentsController(
            ICommentService comments,
            UserManager<User> userManager)
        {
            this.comments = comments;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Add()
            => View();

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(int id, string comment)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(User);

            await this.comments.AddAsync(comment, userId, id);

            return RedirectToAction(nameof(AquariumsController.Details), "Aquariums", new { id });
        }

        public async Task<IActionResult> Delete(int commentId, int id, string comment)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(User);

            await this.comments.DeletetAsync(commentId);

            return RedirectToAction(nameof(AquariumsController.Details), "Aquariums", new { id });
        }
    }
}

ReefAquarium.Web/Controllers/FishController.cs
namespace ReefAquarium.Web.Controllers
{
    using Data;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Models.Fish;
    using Services;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class FishController : Controller
    {
        private readonly IFishService fish;
        private readonly ReefAquariumDbContext db;

        public FishController(
            IFishService fish,
            ReefAquariumDbContext db)
        {
            this.fish = fish;
            this.db = db;
        }

        public async Task<IActionResult> Add(int id)
            => View(new AddFishFormModel
            {
                Breeds = await this.GetBreeds(),
                AquariumId = id
            });

        [HttpPost]
        public async Task<IActionResult> Add(AddFishFormModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Breeds = await this.GetBreeds();
                return View(model);
            }

            await this.fish.AddAsync(
                model.Quantity,
                model.BreedId,
                model.AquariumId);

            var id = model.AquariumId;

            return RedirectToAction(nameof(AquariumsController.Details), "Aquariums", new { id });
        }

        [HttpPost]
        public async Task<IActionResult> PlusOne(int fishId, int id)
        {
            await this.fish.PlusOne(fishId);

            return RedirectToAction(nameof(AquariumsController.Details), "Aquariums", new { id });
        }

        [HttpPost]
        public async Task<IActionResult> SubstractOne(int fishId, int id)
        {
            await this.fish.SubstractOne(fishId);

            return RedirectToAction(nameof(AquariumsController.Details), "Aquariums", new { id });
        }

        private async Task<IEnumerable<SelectListItem>> GetBreeds()
        {
            var breeds = await this.db.Breeds
                .Select(b => new SelectListItem
                {
                    Text = b.Name,
                    Value = b.Id.ToString()
                })
                .ToListAsync();

            return breeds;
        }
    }
}

ReefAquarium.Web/Views/Aquariums/All.cshtml
@model IEnumerable<AquariumListingServiceModel>
@{
    ViewData["Title"] = "All Aquariums";
}
<h2>@ViewData["Title"]</h2>
<div class="row">
    @foreach (var aquarium in Model)
    {
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">
                        <a asp-controller="Aquariums" asp-action="Details" asp-route-id="@aquarium.Id">@aquarium.Title</a>
                    </h3>
                </div>
                <div class="panel-body">
                    <img src="@aquarium.ImageUrl" class="img-responsive">
                    <br />
                    <p class="text-center">@aquarium.Owner</p>
                </div>
            </div>
        </div>
    }
</div>

ReefAquarium.Web/Views/Aquariums/Create.cshtml
@model AquariumFormModel
@{
    ViewData["Title"] = "Create Aquarium";
}
<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-4">
        @Html.Partial("_AquariumForm", Model);
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ReefAquarium.Web/Views/Aquariums/Details.cshtml
@model AquariumDetailsServiceModel
@{
    ViewData["Title"] = Model.Title;
}
<h2 class="text-center">
    @ViewData["Title"]
    @if (User.Identity.IsAuthenticated)
    {
        if (Model.UserIsOwner)
        {
            <a class="btn btn-sm btn-primary" asp-controller="Aquariums" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        }
    }
    </h2>

<div>
    <hr />
    <br />    
    <dl class="dl-horizontal">
        <dd>
            <img src="@Model.ImageUrl" height="500" width="1000"/>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Length) cm
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Width) cm
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Height) cm
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Volume)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Volume) L
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fish)
        </dt>
        <dd>
            <ul>
                @foreach (var fish in Model.Fish)
                {
                    <li>
                        <a asp-controller="Breeds" asp-action="Details" asp-route-id="@fish.BreedId">@fish.BreedName</a> x @fish.Quantity

                        @if (Model.UserIsOwner)
                        {
                                <form asp-controller="Fish" asp-action="SubstractOne" asp-route-fishId="@fish.Id" asp-route-id="@Model.Id">
                                    <input type="submit" class="btn btn-warning btn-sm" value="-" />
                                </form>
                                <form asp-controller="Fish" asp-action="PlusOne" asp-route-fishId="@fish.Id" asp-route-id="@Model.Id">
                                    <input type="submit" class="btn btn-primary btn-sm" value="+" />
                                </form>
                        }
                        
                    </li>
                }
            </ul>
        </dd>
        @if (User.Identity.IsAuthenticated)
        {
            if (Model.UserIsOwner)
            {
                <dd>
                    <div>
                        <a class="btn btn-sm btn-default" asp-controller="Fish" asp-action="Add" asp-route-id="@Model.Id" method="get">Add Fish</a>
                    </div>

                </dd>
            }
        }
        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>
    </dl>
</div>
<h4 >Comments:</h4>
<hr />
@if (User.Identity.IsAuthenticated)
{
    <div>
        <form asp-controller="Comments" asp-action="Add" asp-route-id="@Model.Id" method="post">
            <textarea cols="60" rows="3" name="comment" id="comment"></textarea>
            <br />
            <input type="submit" class="btn btn-primary" value="Add Comment" />
        </form>
    </div>
}
else
{
    <span>To comment in this aquarium, please <a asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">login</a> into your account.</span>
}
<br />
<div>
    @foreach (var comment in Model.Comments)
    {
        <div class="table-bordered">
            <p>@comment.Author : @comment.Content</p>
            <p class="small">@comment.PublishDate.ToShortDateString()</p>
        </div>
    }
</div>
<div>
    <a class="btn btn-default btn-sm" asp-action="All">Back to List</a>
</div>

ReefAquarium.Web/Views/Aquariums/Edit.cshtml
@model AquariumFormModel

@{
    ViewData["Title"] = $"Edit {Model.Title} Aquarium";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-4">
        @Html.Partial("_AquariumForm", Model)
    </div>
</div>

ReefAquarium.Web/Views/Aquariums/_AquariumForm.cshtml
@model AquariumFormModel

<form method="post">
    <h4>Create a new account.</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Length"></label>
        <input asp-for="Length" class="form-control" />
        <span asp-validation-for="Length" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Width"></label>
        <input asp-for="Width" class="form-control" />
        <span asp-validation-for="Width" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Height"></label>
        <input asp-for="Height" class="form-control" />
        <span asp-validation-for="Height" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-default">Save Aquarium</button>
</form>